/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OO_Billing_s;

import com.sun.org.apache.xpath.internal.axes.ChildIterator;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.JCheckBox;
import java.util.Calendar;
import java.text.SimpleDateFormat;
      
/**
 *
 * @author Hamza
 */
public class electronics extends javax.swing.JFrame {
Pelectronics OnlyNumbers = new Pelectronics();
    Connection conn;
 ResultSet rs;
 PreparedStatement pst;

   
    public electronics() {
        initComponents();
      conn=JavaConnection.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        chk0 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jTextField19 = new javax.swing.JTextField();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jCheckBox23 = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 8), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 300, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name of Customer");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 350, 50));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele logo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 520, 150));

        jLabel6.setBackground(new java.awt.Color(255, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele 4.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 320, 150));

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele 3.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 7)));
        jPanel1.setLayout(null);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setText("AIR CONDITONER");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(30, 50, 140, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 50, 80, 40);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setText("REFREGERATOR");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(30, 150, 121, 40);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox4.setText("5%");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(180, 360, 90, 40);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox5.setText("Bulbs");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(31, 249, 110, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 100, 80, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 150, 80, 40);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(170, 200, 80, 40);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 250, 80, 40);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(650, 50, 150, 40);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox6.setText("MICROWAVE");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(30, 100, 120, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 420, 310, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(360, 20, 420, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Total Cost of Items");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 60, 140, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("                                                              D i s c o u n t");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 320, 750, 24);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox8.setText("FAN");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(30, 200, 110, 40);

        buttonGroup1.add(jCheckBox9);
        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox9.setText("10%");
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(280, 360, 90, 40);

        buttonGroup1.add(jCheckBox10);
        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox10.setText("30%");
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(620, 360, 100, 40);

        buttonGroup1.add(jCheckBox11);
        jCheckBox11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox11.setText("15%");
        jPanel1.add(jCheckBox11);
        jCheckBox11.setBounds(400, 360, 100, 40);

        buttonGroup1.add(chk0);
        chk0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk0.setText("0%");
        jPanel1.add(chk0);
        chk0.setBounds(80, 360, 90, 40);

        buttonGroup1.add(jCheckBox13);
        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox13.setText("20%");
        jPanel1.add(jCheckBox13);
        jCheckBox13.setBounds(500, 360, 100, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("SubTotal");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 110, 80, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Total");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(510, 160, 90, 20);

        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jTextField12);
        jTextField12.setBounds(650, 100, 150, 40);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jTextField13);
        jTextField13.setBounds(650, 150, 150, 40);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(30, 310, 750, 20);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(440, 410, 340, 10);

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox14.setText("HEATER");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox14);
        jCheckBox14.setBounds(260, 50, 120, 40);

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox15.setText("VACUUMS");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox15);
        jCheckBox15.setBounds(260, 100, 100, 40);

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox16.setText("WASHING MACHINE");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox16);
        jCheckBox16.setBounds(260, 150, 150, 40);

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox17.setText("COMPUTER");
        jCheckBox17.setToolTipText("");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox17);
        jCheckBox17.setBounds(260, 200, 110, 40);

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox18.setText("TELIVISION");
        jCheckBox18.setToolTipText("");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox18);
        jCheckBox18.setBounds(260, 250, 110, 40);

        jTextField14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField14KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(410, 250, 80, 40);

        jTextField15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField15KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField15);
        jTextField15.setBounds(410, 200, 80, 40);

        jTextField16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField16);
        jTextField16.setBounds(410, 150, 80, 40);

        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField17KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField17);
        jTextField17.setBounds(410, 100, 80, 40);

        jTextField18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField18KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField18);
        jTextField18.setBounds(410, 50, 80, 40);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(30, 30, 410, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 12)));
        jPanel4.setLayout(null);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox19.setText("Crispy Burger");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox19);
        jCheckBox19.setBounds(30, 50, 120, 40);

        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField19KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField19);
        jTextField19.setBounds(150, 50, 80, 40);

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox20.setText("Icecream");
        jPanel4.add(jCheckBox20);
        jCheckBox20.setBounds(30, 150, 80, 40);

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox21.setText("5%");
        jPanel4.add(jCheckBox21);
        jCheckBox21.setBounds(70, 400, 90, 40);

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox22.setText("Onion Rings");
        jPanel4.add(jCheckBox22);
        jCheckBox22.setBounds(31, 249, 110, 40);

        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField20KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField20);
        jTextField20.setBounds(150, 100, 80, 40);

        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField21KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField21KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField21);
        jTextField21.setBounds(150, 150, 80, 40);

        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField22KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField22KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField22);
        jTextField22.setBounds(150, 200, 80, 40);

        jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField23KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField23KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField23);
        jTextField23.setBounds(150, 250, 80, 40);

        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jTextField24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField24KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField24);
        jTextField24.setBounds(640, 50, 150, 40);

        jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField25KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField25);
        jTextField25.setBounds(640, 100, 150, 40);

        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField26KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField26KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField26);
        jTextField26.setBounds(640, 150, 150, 40);

        jTextField27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField27KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField27);
        jTextField27.setBounds(640, 200, 150, 40);

        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField28KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField28);
        jTextField28.setBounds(640, 250, 150, 40);

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox23.setText("Fries");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox23);
        jCheckBox23.setBounds(30, 100, 80, 40);
        jPanel4.add(jSeparator7);
        jSeparator7.setBounds(20, 500, 420, 30);
        jPanel4.add(jSeparator8);
        jSeparator8.setBounds(360, 20, 420, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Total Cost of Mileage");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(480, 160, 160, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Total Cost of Items");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(480, 60, 140, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setText("Total Cost of Delivery");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(480, 110, 150, 20);

        jCheckBox24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox24.setText("VAT");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox24);
        jCheckBox24.setBounds(480, 260, 63, 31);

        jCheckBox25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBox25.setText("Tax");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox25);
        jCheckBox25.setBounds(480, 210, 55, 31);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("       Discount");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel17);
        jLabel17.setBounds(90, 320, 140, 40);

        jCheckBox26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox26.setText("Chicken Salad");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox26);
        jCheckBox26.setBounds(31, 195, 130, 40);

        jCheckBox27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox27.setText("10%");
        jPanel4.add(jCheckBox27);
        jCheckBox27.setBounds(70, 440, 90, 40);

        jCheckBox28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox28.setText("30%");
        jPanel4.add(jCheckBox28);
        jCheckBox28.setBounds(210, 440, 100, 40);

        jCheckBox29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox29.setText("15%");
        jPanel4.add(jCheckBox29);
        jCheckBox29.setBounds(210, 360, 100, 40);

        jCheckBox30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox30.setText("0%");
        jPanel4.add(jCheckBox30);
        jCheckBox30.setBounds(70, 360, 90, 40);

        jCheckBox31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox31.setText("20%");
        jPanel4.add(jCheckBox31);
        jCheckBox31.setBounds(210, 400, 100, 40);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Tax");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(390, 330, 90, 20);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("SubTotal");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(390, 390, 80, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Total");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(390, 450, 90, 20);

        jTextField29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField29);
        jTextField29.setBounds(480, 320, 160, 40);

        jTextField30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel4.add(jTextField30);
        jTextField30.setBounds(480, 380, 160, 40);

        jTextField31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel4.add(jTextField31);
        jTextField31.setBounds(480, 440, 160, 40);
        jPanel4.add(jSeparator9);
        jSeparator9.setBounds(30, 310, 750, 20);
        jPanel4.add(jSeparator10);
        jSeparator10.setBounds(360, 490, 420, 10);

        jCheckBox32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox32.setText("Zinger Burger");
        jPanel4.add(jCheckBox32);
        jCheckBox32.setBounds(250, 50, 120, 40);

        jCheckBox33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox33.setText("Coke");
        jCheckBox33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox33ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox33);
        jCheckBox33.setBounds(250, 100, 80, 40);

        jCheckBox34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox34.setText(" Church’s Chicken");
        jPanel4.add(jCheckBox34);
        jCheckBox34.setBounds(250, 150, 140, 40);

        jCheckBox35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox35.setText("Cheeseburger");
        jCheckBox35.setToolTipText("");
        jCheckBox35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox35ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox35);
        jCheckBox35.setBounds(250, 200, 130, 40);

        jCheckBox36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox36.setText(" ButterBurger");
        jCheckBox36.setToolTipText("");
        jPanel4.add(jCheckBox36);
        jCheckBox36.setBounds(250, 250, 130, 40);

        jTextField32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField32KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField32KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField32);
        jTextField32.setBounds(390, 250, 80, 40);

        jTextField33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField33KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField33KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField33);
        jTextField33.setBounds(390, 200, 80, 40);

        jTextField34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField34KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField34KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField34);
        jTextField34.setBounds(390, 150, 80, 40);

        jTextField35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField35KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField35KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField35);
        jTextField35.setBounds(390, 100, 80, 40);

        jTextField36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jTextField36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField36KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField36KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField36);
        jTextField36.setBounds(390, 50, 80, 40);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator11);
        jSeparator11.setBounds(330, 330, 110, 140);
        jPanel4.add(jSeparator12);
        jSeparator12.setBounds(30, 30, 400, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Calclulator");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(330, 400, 110, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 810, 440));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 7)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1214, 1214, 1214)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 470, 520));

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 180, 50));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, 180, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 180, 50));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 180, 50));

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele 2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 340, 80));

        jLabel7.setBackground(new java.awt.Color(255, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele 2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 340, 80));

        jLabel8.setBackground(new java.awt.Color(255, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OO_Billing_s/ele 2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 340, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Pelectronics Cost_of_items= new Pelectronics();
     double ItemTax, iSubtotal, iTotal; 
     Cost_of_items.Crispy_Burger = Cost_of_items.air * Double.parseDouble(jTextField1.getText());
     Cost_of_items.Fries = Cost_of_items.micro * Double.parseDouble(jTextField2.getText());
     Cost_of_items.Icecream = Cost_of_items.ref * Double.parseDouble(jTextField3.getText());
     Cost_of_items.Chicken_salad = Cost_of_items.fan * Double.parseDouble(jTextField4.getText());
     Cost_of_items.Onion_rings = Cost_of_items.lights * Double.parseDouble(jTextField5.getText());
     Cost_of_items.Zinger_Burger = Cost_of_items.heater * Double.parseDouble(jTextField18.getText());
     Cost_of_items.Coke = Cost_of_items.vacuum * Double.parseDouble(jTextField17.getText());
     Cost_of_items.Crunch_Chicken = Cost_of_items.washing * Double.parseDouble(jTextField16.getText());
     Cost_of_items.Cheese_Burger= Cost_of_items.computer * Double.parseDouble(jTextField15.getText());
     Cost_of_items.Butter_Burger = Cost_of_items.television * Double.parseDouble(jTextField14.getText());
     
    
     if(chk0.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs%.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs%.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     //----------------------------------------------------------------------------------------
     
     if(jCheckBox4.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
       iSubtotal =   iSubtotal-((iSubtotal * 5)/100);
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs %.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs %.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     
     //=========================================================================
     
          if(jCheckBox9.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
       iSubtotal =   iSubtotal-((iSubtotal * 10)/100);
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs %.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs %.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     //===========================================================================
          if(jCheckBox11.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
       iSubtotal =   iSubtotal-((iSubtotal * 15)/100);
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs %.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs %.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     //==========================================================================
          if(jCheckBox13.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
       iSubtotal =   iSubtotal-((iSubtotal * 10)/100);
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs %.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs %.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     //============================================================================
          if(jCheckBox10.isSelected()){
      
      iSubtotal =   Cost_of_items.GetAmount();
       iSubtotal =   iSubtotal-((iSubtotal * 30)/100);
     
     iTotal = iSubtotal;
     
     String SubTotal = String.format("Rs %.2f ",iSubtotal);
     jTextField12.setText(SubTotal);
     
    
          String Total = String.format("Rs %.2f ",iTotal);
     jTextField13.setText(Total);
     
     jTextField6.setText(String.format("Rs %.2f",Cost_of_items.Crispy_Burger + Cost_of_items.Fries+Cost_of_items.Icecream+Cost_of_items.Chicken_salad+Cost_of_items.Onion_rings 
      +Cost_of_items.Zinger_Burger+Cost_of_items.Coke+Cost_of_items.Crunch_Chicken+Cost_of_items.Cheese_Burger+Cost_of_items.Butter_Burger));
     }
     
     //------------------------------------------------------------------------------
      JTextField clearText = null;
     for(Component c:jPanel1.getComponents()){
     if(c.getClass().toString().contains("javax.swing.JTextField")){
     clearText = (JTextField)c;
  
          clearText.setEnabled(true);
     }
     
     }
     String sql="Insert into Electronics(Name,Air_Con,Microwave,Refg,Fan,Bulbs,Heater,Vacuum,Washing_M,Computers,TV,Total,Discount)values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
           pst=conn.prepareStatement(sql);
           pst.setString(1,jTextField7.getText());
           pst.setString(2,jTextField1.getText());
           pst.setString(3,jTextField2.getText());
           pst.setString(4,jTextField3.getText());
           pst.setString(5,jTextField4.getText());
           pst.setString(6,jTextField5.getText());
           pst.setString(7,jTextField18.getText());
           pst.setString(8,jTextField17.getText());
           pst.setString(9,jTextField16.getText());
           pst.setString(10,jTextField15.getText());
           pst.setString(11,jTextField14.getText());
           pst.setString(12,jTextField13.getText());
           chk0.setActionCommand("o%");
           jCheckBox4.setActionCommand("5%");
           jCheckBox9.setActionCommand("10%");
            jCheckBox11.setActionCommand("15%");
             jCheckBox13.setActionCommand("20%");
              jCheckBox10.setActionCommand("30%");
              pst.setString(13, buttonGroup1.getSelection().getActionCommand());
           
           pst.execute();
          // pst.setString(4,(String)jComboBox1.getSelectedItem());
           // jRadioButton1.setActionCommand("Male");
           // jRadioButton2.setActionCommand("FeMale");
           // pst.setString(5,buttonGroup1.getSelection().getActionCommand()); 
          // pst.setString(6,jTextField4.getText());
          
          
    //    pst.setString(8,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
          
          // pst.setString(11,jTextField8.getText());
             
           
        //JOptionPane.showMessageDialog(null, "Congratulaion ! Account has been created"); 
          
          // a=1;
          
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);   
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
          if (jCheckBox8.isSelected()){
     jTextField4.setEnabled(true);
     jTextField4.setText("");
     jTextField4.requestFocus();
   
   }          
   else
   {
   jTextField4.setEnabled(false);
     jTextField4.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
          if (jCheckBox17.isSelected()){
     jTextField15.setEnabled(true);
     jTextField15.setText("");
     jTextField15.requestFocus();
   
   }          
   else
   {
   jTextField15.setEnabled(false);
     jTextField15.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
          if (jCheckBox15.isSelected()){
     jTextField17.setEnabled(true);
     jTextField17.setText("");
     jTextField17.requestFocus();
   
   }          
   else
   {
   jTextField17.setEnabled(false);
     jTextField17.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Main2 obj = new Main2();
       obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       
       
        try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
       
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField18KeyPressed

    private void jTextField17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField17KeyPressed

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField16KeyPressed

    private void jTextField15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyPressed
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField15KeyPressed

    private void jTextField14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyPressed
        try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField14KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
         try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
          try{
       OnlyNumbers.NumbersOnly(evt);
       }catch (NumberFormatException e){
       
           JOptionPane.showConfirmDialog(null, " Billing System Error ");
       }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
   if (jCheckBox2.isSelected()){
     jTextField1.setEnabled(true);
     jTextField1.setText("");
     jTextField1.requestFocus();
   
   }          
   else
   {
   jTextField1.setEnabled(false);
     jTextField1.setText("");
   
   }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        jTextArea2.setText("");
        
        JTextField clearText = null;
     for(Component c:jPanel1.getComponents()){
     if(c.getClass().toString().contains("javax.swing.JTextField")){
     clearText = (JTextField)c;
     clearText.setText("0");
          clearText.setEnabled(false);
     }
     
     }
       JCheckBox checkers = null;
     for(Component q:jPanel1.getComponents()){
     if(q.getClass().toString().contains("javax.swing.JCheckBox")){
     checkers = (JCheckBox)q;
     checkers.setSelected(false);
     
     
     }
     
     }
       buttonGroup1.clearSelection();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
   JTextField clearText = null;
     for(Component c:jPanel1.getComponents()){
     if(c.getClass().toString().contains("javax.swing.JTextField")){
     clearText = (JTextField)c;
     clearText.setText("0");
     clearText.setEnabled(false);
     
     }
     
     }

    }//GEN-LAST:event_formWindowActivated

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed

          if (jCheckBox6.isSelected()){
     jTextField2.setEnabled(true);
     jTextField2.setText("");
     jTextField2.requestFocus();
   
   }          
   else
   {
   jTextField2.setEnabled(false);
     jTextField2.setText("");
   
   }
    
        
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField19KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19KeyPressed

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20KeyPressed

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20KeyTyped

    private void jTextField21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField21KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21KeyPressed

    private void jTextField21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField21KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21KeyTyped

    private void jTextField22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField22KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22KeyPressed

    private void jTextField22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField22KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22KeyTyped

    private void jTextField23KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23KeyPressed

    private void jTextField23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23KeyTyped

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField24KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24KeyTyped

    private void jTextField25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField25KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25KeyTyped

    private void jTextField26KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField26KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26KeyPressed

    private void jTextField26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField26KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26KeyTyped

    private void jTextField27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27KeyTyped

    private void jTextField28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28KeyTyped

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox26ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jCheckBox33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox33ActionPerformed

    private void jCheckBox35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox35ActionPerformed

    private void jTextField32KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField32KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32KeyPressed

    private void jTextField32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField32KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32KeyTyped

    private void jTextField33KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField33KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33KeyPressed

    private void jTextField33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField33KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33KeyTyped

    private void jTextField34KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField34KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34KeyPressed

    private void jTextField34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField34KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34KeyTyped

    private void jTextField35KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField35KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35KeyPressed

    private void jTextField35KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField35KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35KeyTyped

    private void jTextField36KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField36KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36KeyPressed

    private void jTextField36KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField36KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
      
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()){
     jTextField3.setEnabled(true);
     jTextField3.setText("");
     jTextField3.requestFocus();
   
   }          
   else
   {
   jTextField3.setEnabled(false);
     jTextField3.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if (jCheckBox5.isSelected()){
     jTextField5.setEnabled(true);
     jTextField5.setText("");
     jTextField5.requestFocus();
   
   }          
   else
   {
   jTextField5.setEnabled(false);
     jTextField5.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
          if (jCheckBox14.isSelected()){
     jTextField18.setEnabled(true);
     jTextField18.setText("");
     jTextField18.requestFocus();
   
   }          
   else
   {
   jTextField18.setEnabled(false);
     jTextField18.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
         if (jCheckBox16.isSelected()){
     jTextField16.setEnabled(true);
     jTextField16.setText("");
     jTextField16.requestFocus();
   
   }          
   else
   {
   jTextField16.setEnabled(false);
     jTextField16.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
          if (jCheckBox18.isSelected()){
     jTextField14.setEnabled(true);
     jTextField14.setText("");
     jTextField14.requestFocus();
   
   }          
   else
   {
   jTextField14.setEnabled(false);
     jTextField14.setText("");
   
   }
    
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //===============================================
        
        int refs = 1325 + (int) (Math.random() * 4238);
        
        //=================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
         
        jTextArea2.append("\t Electronics Bill:\n" + 
                  "Reference: \t\t\t" + refs + "\n" +
               "Name\t\t\t" + jTextField7.getText() +
          "\n================================================\n" +
                "AIR CONDITIONAR (Rs:80000)\t\t" + jTextField1.getText() + "\n\n" +
                 "MICROWAVE (Rs:35000)\t\t" + jTextField2.getText() + "\n\n" +
                 "REFRIGERATOR (Rs:60000)\t\t" + jTextField3.getText() + "\n\n" +
                 "FAN (Rs:8000)\t\t\t" + jTextField4.getText() + "\n\n" +
                 "LIGHT (Rs:1000)\t\t" + jTextField5.getText() + "\n\n" +
                 "HEATER (Rs:5000)\t\t" + jTextField18.getText() + "\n\n" +
                 "VACUUM (Rs:4000)\t\t" + jTextField17.getText() + "\n\n" +
                 "WASHING MACHINE (Rs:20000)\t" + jTextField16.getText() + "\n\n" +
                 "COMPUTER (Rs:45000)\t\t" + jTextField15.getText() + "\n\n" +
                 "TELIVISION (Rs:30000)\t\t" + jTextField14.getText() + "\n" +
            "==================================================" + "\n" +
                "cost of items:\t\t\t" + jTextField6.getText() + "\n" +
                "SubTotal:\t\t\t" + jTextField12.getText() + "\n" +
                "Total:\t\t\t" + jTextField13.getText() + "\n" +
                
            "==================================================" + "\n" +
                "\nDate: " + Tdate.format(timer.getTime()) +
                "\tTime: " + tTime.format(timer.getTime()) + "\n" +
            "=================== Thank You ======================"    
                );
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        c5 obj = new c5();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Billings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Billings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
